/**
 * Auto-generated image manifest
 * Generated by: scripts/optimize-images.js
 * DO NOT EDIT MANUALLY
 */

export const IMAGE_MANIFEST = {
  "cardamom-farm.png": {
    "original": "cardamom-farm.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "webp": "/images/optimized/cardamom-farm.webp",
      "avif": "/images/optimized/cardamom-farm.avif"
    },
    "responsive": [
      {
        "width": 320,
        "webp": "/images/optimized/cardamom-farm-sm.webp",
        "avif": "/images/optimized/cardamom-farm-sm.avif"
      },
      {
        "width": 640,
        "webp": "/images/optimized/cardamom-farm-md.webp",
        "avif": "/images/optimized/cardamom-farm-md.avif"
      }
    ],
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAUABQDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAQCAwX/xAAZEAEBAQEBAQAAAAAAAAAAAAAAAQITAxH/xAAXAQEBAQEAAAAAAAAAAAAAAAAAAQID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A8bGnbPoiztro4NLeoh6gqf7S2gDNtAEf/9k="
  },
  "cardamom-pod-3d.png": {
    "original": "cardamom-pod-3d.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "webp": "/images/optimized/cardamom-pod-3d.webp",
      "avif": "/images/optimized/cardamom-pod-3d.avif"
    },
    "responsive": [
      {
        "width": 320,
        "webp": "/images/optimized/cardamom-pod-3d-sm.webp",
        "avif": "/images/optimized/cardamom-pod-3d-sm.avif"
      },
      {
        "width": 640,
        "webp": "/images/optimized/cardamom-pod-3d-md.webp",
        "avif": "/images/optimized/cardamom-pod-3d-md.avif"
      }
    ],
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAUABQDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAECAwb/xAAXEAEBAQEAAAAAAAAAAAAAAAAAAQIS/8QAFgEBAQEAAAAAAAAAAAAAAAAAAQAC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A9NanRpmMl0lEggWJICLUgBD/2Q=="
  },
  "cardamom-pods.png": {
    "original": "cardamom-pods.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "webp": "/images/optimized/cardamom-pods.webp",
      "avif": "/images/optimized/cardamom-pods.avif"
    },
    "responsive": [
      {
        "width": 320,
        "webp": "/images/optimized/cardamom-pods-sm.webp",
        "avif": "/images/optimized/cardamom-pods-sm.avif"
      },
      {
        "width": 640,
        "webp": "/images/optimized/cardamom-pods-md.webp",
        "avif": "/images/optimized/cardamom-pods-md.avif"
      }
    ],
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAUABQDASIAAhEBAxEB/8QAGAABAAMBAAAAAAAAAAAAAAAAAAECAwX/xAAYEAEBAQEBAAAAAAAAAAAAAAAAEQECEv/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A4G8q7y1qNRGPkaQBW6mgqlAB/9k="
  },
  "hero-bg.png": {
    "original": "cardamom-farm.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "webp": "/images/optimized/cardamom-farm.webp",
      "avif": "/images/optimized/cardamom-farm.avif",
      "png": "/images/cardamom-farm.png"
    },
    "responsive": [
      {
        "width": 320,
        "webp": "/images/optimized/cardamom-farm-sm.webp",
        "avif": "/images/optimized/cardamom-farm-sm.avif"
      },
      {
        "width": 640,
        "webp": "/images/optimized/cardamom-farm-md.webp",
        "avif": "/images/optimized/cardamom-farm-md.avif"
      }
    ],
    "blurDataUrl": "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAUABQDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAQCAwX/xAAZEAEBAQEBAQAAAAAAAAAAAAAAAQITAxH/xAAXAQEBAQEAAAAAAAAAAAAAAAAAAQID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A8bGnbPoiztro4NLeoh6gqf7S2gDNtAEf/9k="
  },
  "cardamom-hero.png": {
    "original": "cardamom-hero.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "png": "/images/cardamom-hero.png"
    }
  },
  "cardamom-closeup.png": {
    "original": "cardamom-closeup.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "png": "/images/cardamom-closeup.png"
    }
  },
  "arabic-coffee.png": {
    "original": "arabic-coffee.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "png": "/images/arabic-coffee.png"
    }
  },
  "indian-biryani.png": {
    "original": "indian-biryani.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "png": "/images/indian-biryani.png"
    }
  },
  "royal-feast.png": {
    "original": "royal-feast.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "png": "/images/royal-feast.png"
    }
  },
  "scandinavian-buns.png": {
    "original": "scandinavian-buns.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "png": "/images/scandinavian-buns.png"
    }
  },
  "health-ayurveda.png": {
    "original": "health-ayurveda.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "png": "/images/health-ayurveda.png"
    }
  },
  "emperor-packaging.png": {
    "original": "emperor-packaging.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "png": "/images/emperor-packaging.png"
    }
  },
  "india-map.png": {
    "original": "india-map.png",
    "width": 1024,
    "height": 1024,
    "formats": {
      "png": "/images/india-map.png"
    }
  }
};

/**
 * Get optimized image sources for a given image path
 * @param {string} originalPath - Original image path (e.g., '/images/cardamom-pods.png')
 * @returns {Object} Optimized image data including formats, responsive sizes, and blur placeholder
 */
export function getOptimizedImage(originalPath) {
  // Normalize path
  const normalized = originalPath.replace(/^\/images\//, '');
  return IMAGE_MANIFEST[normalized] || null;
}

/**
 * Generate srcset string for responsive images
 * @param {Object} imageData - Image data from manifest
 * @param {string} format - 'webp' or 'avif'
 * @returns {string} srcset string
 */
export function generateSrcSet(imageData, format = 'webp') {
  if (!imageData || !imageData.responsive || imageData.responsive.length === 0) {
    return imageData?.formats?.[format] || '';
  }

  const srcset = imageData.responsive
    .map(r => `${r[format]} ${r.width}w`)
    .join(', ');

  // Add full size as the largest option
  if (imageData.formats?.[format]) {
    return `${srcset}, ${imageData.formats[format]} ${imageData.width}w`;
  }

  return srcset;
}

/**
 * Get the default sizes attribute based on common breakpoints
 */
export function getDefaultSizes() {
  return '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw';
}
